
package Forms;

import Entities.ItemStock;
import Services.ItemStockService;
import java.awt.Frame;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

public class ShowItemStock extends javax.swing.JFrame {
    
    Frame frame;
    List<ItemStock> itemStocks;
    
    TableColumnModel columnModel;
    Vector<Vector> dataTable;
    Vector<String> columns;
    
    public ShowItemStock() {
        initComponents();
        initializeData();
    }
    
    public ShowItemStock(Frame frame) {
        initComponents();
        this.frame = frame;
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStocks = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1936, 1038));
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        tblStocks.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblStocks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Description", "Quantity", "Unit", "Unit Price", "Currency", "Total Amount", "Supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStocks.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblStocks);
        if (tblStocks.getColumnModel().getColumnCount() > 0) {
            tblStocks.getColumnModel().getColumn(0).setResizable(false);
            tblStocks.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblStocks.getColumnModel().getColumn(1).setResizable(false);
            tblStocks.getColumnModel().getColumn(1).setPreferredWidth(445);
            tblStocks.getColumnModel().getColumn(2).setResizable(false);
            tblStocks.getColumnModel().getColumn(2).setPreferredWidth(113);
            tblStocks.getColumnModel().getColumn(3).setResizable(false);
            tblStocks.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblStocks.getColumnModel().getColumn(4).setResizable(false);
            tblStocks.getColumnModel().getColumn(4).setPreferredWidth(166);
            tblStocks.getColumnModel().getColumn(5).setResizable(false);
            tblStocks.getColumnModel().getColumn(5).setPreferredWidth(90);
            tblStocks.getColumnModel().getColumn(6).setResizable(false);
            tblStocks.getColumnModel().getColumn(6).setPreferredWidth(183);
            tblStocks.getColumnModel().getColumn(7).setResizable(false);
            tblStocks.getColumnModel().getColumn(7).setPreferredWidth(713);
        }

        btnBack.setText("BACK");
        btnBack.setToolTipText("");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1488, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(704, 704, 704))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            dispose();
            frame.setVisible(true);
        });
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowItemStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowItemStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowItemStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowItemStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowItemStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStocks;
    // End of variables declaration//GEN-END:variables

    private void initializeData() {
        columns = new Vector<>();
        dataTable = new Vector<>();
        columns.add("Item Code");
        columns.add("Description");
        columns.add("Qty");
        columns.add("Unit");
        columns.add("Unit Price");
        columns.add("Currency");
        columns.add("Total Amount");
        columns.add("Supplier");
        itemStocks = ItemStockService.findAll();
        
        for(int i=0; i<itemStocks.size(); i++) {
            ItemStock itemStock = itemStocks.get(i);
            int quantity = itemStock.getQuantity();
            BigDecimal unitPrice = itemStock.getUnitPrice();
            BigDecimal totalAmount = unitPrice.multiply(new BigDecimal(quantity));
            Vector<Object> row = new Vector<>();
            row.add(itemStock.getItemCode());
            row.add(itemStock.getDescription());
            row.add(quantity);
            row.add(itemStock.getUnit());
            row.add(unitPrice);
            row.add(itemStock.getCurrency());
            row.add(totalAmount);
            row.add(itemStock.getSupplier().getName());
            dataTable.add(row);
        }
        tblStocks.setModel(new DefaultTableModel(dataTable, columns) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        if (tblStocks.getColumnModel().getColumnCount() > 0) {
            tblStocks.getColumnModel().getColumn(0).setResizable(false);
            tblStocks.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblStocks.getColumnModel().getColumn(1).setResizable(false);
            tblStocks.getColumnModel().getColumn(1).setPreferredWidth(445);
            tblStocks.getColumnModel().getColumn(2).setResizable(false);
            tblStocks.getColumnModel().getColumn(2).setPreferredWidth(113);
            tblStocks.getColumnModel().getColumn(3).setResizable(false);
            tblStocks.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblStocks.getColumnModel().getColumn(4).setResizable(false);
            tblStocks.getColumnModel().getColumn(4).setPreferredWidth(166);
            tblStocks.getColumnModel().getColumn(5).setResizable(false);
            tblStocks.getColumnModel().getColumn(5).setPreferredWidth(90);
            tblStocks.getColumnModel().getColumn(6).setResizable(false);
            tblStocks.getColumnModel().getColumn(6).setPreferredWidth(183);
            tblStocks.getColumnModel().getColumn(7).setResizable(false);
            tblStocks.getColumnModel().getColumn(7).setPreferredWidth(713);
        }
    }
}
