
package Forms.WarehouseAdmin;

import ConstantHandlers.ConstantHandler;
import ConstantHandlers.CustomTableModel;
import Entities.ItemStock;
import Entities.Purchases.ItemDelivery;
import Entities.Purchases.ItemOrder;
import Entities.Purchases.PurchaseOrder;
import Entities.Purchases.ReceivingReport;
import Forms.Login;
import Services.ItemDeliveryService;
import Services.ItemStockService;
import Services.PurchaseOrderService;
import Services.ReceivingReportService;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class AddReceiving extends javax.swing.JFrame {

    Frame frame;
    List<PurchaseOrder> purchaseOrders;
    List<ItemOrder> itemOrders;
    Vector<String> columns;
    Vector<String> deliveryColumn;
    Vector<Vector> deliveries;
    BigDecimal deliveryTotalAmount = new BigDecimal(0);
    
    public AddReceiving() {
        initComponents();
        initializeData();
    }
    
    public AddReceiving(Frame frame) {
        initComponents();
        this.frame = frame;
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemOrders = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblSupplierCode = new javax.swing.JLabel();
        cbxPoNo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblProjectName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblProjectCode = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPoDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDeliveryPlace = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        lblDeliveryDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        txtPOTotalAmount = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtReceivingWarehouse = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtRRNo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDeliveries = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDeliveryTotalAmount = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jdcDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtCheckedBy = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtApprovedBy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPreparedBy = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1936, 1038));
        setExtendedState(6);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1936, 1038));
        setSize(new java.awt.Dimension(1936, 1038));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(0, 0, 0)));

        tblItemOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Qty", "Unit", "Currency", "Unit Price", "Total Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItemOrders);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("PURCHASE ORDER INFORMATION");

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        lblSupplierCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSupplierCode.setPreferredSize(new java.awt.Dimension(109, 28));

        cbxPoNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxPoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPoNoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Project Name:  ");
        jLabel4.setPreferredSize(new java.awt.Dimension(215, 28));

        lblProjectName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblProjectName.setPreferredSize(new java.awt.Dimension(215, 28));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Supplier Code:  ");
        jLabel5.setPreferredSize(new java.awt.Dimension(215, 28));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Supplier Name:  ");
        jLabel6.setPreferredSize(new java.awt.Dimension(215, 28));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Project Code:  ");
        jLabel3.setPreferredSize(new java.awt.Dimension(215, 28));

        lblProjectCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblProjectCode.setMaximumSize(new java.awt.Dimension(109, 28));
        lblProjectCode.setMinimumSize(new java.awt.Dimension(109, 28));
        lblProjectCode.setPreferredSize(new java.awt.Dimension(109, 28));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Delivery Place:  ");
        jLabel8.setPreferredSize(new java.awt.Dimension(215, 28));

        lblPoDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPoDate.setPreferredSize(new java.awt.Dimension(215, 28));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("P.O. Date:  ");
        jLabel2.setPreferredSize(new java.awt.Dimension(215, 28));

        lblDeliveryPlace.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDeliveryPlace.setPreferredSize(new java.awt.Dimension(215, 28));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Delivery Date:  ");
        jLabel7.setPreferredSize(new java.awt.Dimension(215, 28));

        lblSupplierName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSupplierName.setPreferredSize(new java.awt.Dimension(215, 28));

        lblDeliveryDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDeliveryDate.setPreferredSize(new java.awt.Dimension(215, 28));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("P.O. No:  ");
        jLabel1.setPreferredSize(new java.awt.Dimension(215, 28));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSupplierCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDeliveryDate, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cbxPoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addComponent(lblDeliveryPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(lblPoDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPoNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeliveryPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Department:  ");

        lblDepartment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtPOTotalAmount.setEditable(false);
        txtPOTotalAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPOTotalAmount.setText("0.00");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Total Amount:  ");
        jLabel19.setMaximumSize(new java.awt.Dimension(124, 17));
        jLabel19.setMinimumSize(new java.awt.Dimension(124, 17));
        jLabel19.setPreferredSize(new java.awt.Dimension(124, 17));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPOTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel16))
                    .addComponent(lblDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPOTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));

        txtReceivingWarehouse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Receiving Warehouse:  ");

        txtRRNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tblDeliveries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Qty", "Unit", "Currency", "Unit Price", "Total Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDeliveries);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setText("RECEIVING INFORMATION");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("RR No.  ");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Total Amount:  ");
        jLabel17.setMaximumSize(new java.awt.Dimension(124, 17));
        jLabel17.setMinimumSize(new java.awt.Dimension(124, 17));
        jLabel17.setPreferredSize(new java.awt.Dimension(124, 17));

        txtDeliveryTotalAmount.setEditable(false);
        txtDeliveryTotalAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDeliveryTotalAmount.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeliveryTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRRNo))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReceivingWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtRRNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtReceivingWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeliveryTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));

        jdcDate.setBackground(new java.awt.Color(102, 153, 255));
        jdcDate.setDateFormatString("MMMM-dd-yyyy");
        jdcDate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jdcDate.setPreferredSize(new java.awt.Dimension(115, 17));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("PREPARED BY:  ");
        jLabel11.setMaximumSize(new java.awt.Dimension(124, 17));
        jLabel11.setMinimumSize(new java.awt.Dimension(124, 17));
        jLabel11.setPreferredSize(new java.awt.Dimension(124, 17));

        txtCheckedBy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("APPROVED BY:  ");
        jLabel14.setMaximumSize(new java.awt.Dimension(124, 17));
        jLabel14.setMinimumSize(new java.awt.Dimension(124, 17));
        jLabel14.setPreferredSize(new java.awt.Dimension(124, 17));

        txtApprovedBy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("CHECKED BY:  ");
        jLabel13.setMaximumSize(new java.awt.Dimension(124, 17));
        jLabel13.setMinimumSize(new java.awt.Dimension(124, 17));
        jLabel13.setPreferredSize(new java.awt.Dimension(124, 17));

        txtPreparedBy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("DELIVERY DATE:  ");
        jLabel12.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPreparedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCheckedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApprovedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPreparedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCheckedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApprovedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(821, 821, 821)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        jMenu1.setText("File");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPoNoActionPerformed
        // TODO add your handling code here:
        if(cbxPoNo.getSelectedIndex() >= 0) {
            Vector<Vector> particulars = new Vector<>();
            deliveries = new Vector<>();
            itemOrders = new Vector<>();
            SwingUtilities.invokeLater(() -> {
                PurchaseOrder purchaseOrder = purchaseOrders.get(cbxPoNo.getSelectedIndex());
                lblPoDate.setText(purchaseOrder.getPoDate().toString());
                lblProjectCode.setText(purchaseOrder.getProject().getProjectCode());
                lblProjectName.setText(purchaseOrder.getProject().getProjectName());
                lblSupplierCode.setText(purchaseOrder.getSupplier().getCode());
                lblSupplierName.setText(purchaseOrder.getSupplier().getName());
                lblDeliveryDate.setText(purchaseOrder.getDeliveryDate().toString());
                lblDeliveryPlace.setText(purchaseOrder.getDeliveryPlace().toString());
                purchaseOrder.getItemOrders().forEach(itemOrder -> {
                    Vector<String> itemOrderRow = new Vector<>();
                    Vector<String> deliveryRow = new Vector<>();
                    itemOrderRow.addElement(itemOrder.getItemCode());
                    itemOrderRow.addElement(itemOrder.getDescription());
                    itemOrderRow.addElement(String.valueOf(itemOrder.getQuantity()));
                    itemOrderRow.addElement(itemOrder.getUnit());
                    itemOrderRow.addElement(itemOrder.getCurrency());
                    itemOrderRow.addElement(itemOrder.getUnitPrice().toString());
                    itemOrderRow.addElement(itemOrder.getTotalCost().toString());
                    
                    deliveryRow.addElement(itemOrder.getItemCode());
                    deliveryRow.addElement(itemOrder.getDescription());
                    deliveryRow.addElement("0");
                    deliveryRow.addElement(itemOrder.getUnit());
                    deliveryRow.addElement(itemOrder.getCurrency());
                    deliveryRow.addElement(itemOrder.getUnitPrice().toString());
                    deliveryRow.addElement(itemOrder.getTotalCost().toString());
                    particulars.add(itemOrderRow);
                    deliveries.add(deliveryRow);
                    itemOrders.add(itemOrder);
                });
                DefaultTableModel itemOrderModel = new DefaultTableModel(particulars, columns);
                CustomTableModel deliveriesModel = new CustomTableModel(deliveries, deliveryColumn);
                deliveriesModel.addTableModelListener(new TableModelListener() {
                    
                    @Override
                    public void tableChanged(TableModelEvent e) {
                        int row = e.getFirstRow();
                        int column = e.getColumn();
                        if(column == 2) {
                            try {
                                int qty = Integer.parseInt(deliveriesModel.getValueAt(row, 2).toString());
                                BigDecimal quantity = new BigDecimal(qty); 
                                BigDecimal unitPrice = new BigDecimal(Double.parseDouble(deliveriesModel.getValueAt(row, 5).toString()));
                                deliveryTotalAmount = deliveryTotalAmount.subtract(BigDecimal.valueOf(Double.parseDouble(deliveriesModel.getValueAt(row, 6).toString())));
                                BigDecimal sum = quantity.multiply(unitPrice);
                                deliveriesModel.setValueAt(sum.toString(), row, 6);
                                deliveryTotalAmount = deliveryTotalAmount.add(sum);
                                txtDeliveryTotalAmount.setText(deliveryTotalAmount.toString());
                            } catch(NumberFormatException ex) {
                                ex.printStackTrace();
                            }
                        }
                    }
                    
                });
                
                for(int i=0; i<deliveries.size(); i++) {
                    deliveriesModel.setCellEditable(i, 2, true);
                }
                
                tblItemOrders.setModel(itemOrderModel);
                tblDeliveries.setModel(deliveriesModel);
                
                try {
                    txtPOTotalAmount.setText(purchaseOrder.getTotalAmount().toString());
                } catch(Exception e) {
                    e.printStackTrace();
                }
                deliveryTotalAmount = new BigDecimal(0);
                txtDeliveryTotalAmount.setText("0.00");
            });
            
        }
    }//GEN-LAST:event_cbxPoNoActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        ConstantHandler.user = null;
        SwingUtilities.invokeLater(() -> {
            dispose();
            new Login().setVisible(true);
        });
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(deliveryTotalAmount.equals(new BigDecimal(0))) {
            JOptionPane.showMessageDialog(null, "No Delivery Input Found!!", "EMPTY DELIVERY", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to save?", "CONFIRM TO SAVE", JOptionPane.OK_CANCEL_OPTION, 3);
            if(confirm == 0) {
                SwingUtilities.invokeLater(() -> {
                    PurchaseOrder purchaseOrder = purchaseOrders.get(cbxPoNo.getSelectedIndex());
                    ReceivingReport receivingReport = new ReceivingReport();
                    receivingReport.setRrNo(txtRRNo.getText().trim());
                    receivingReport.setDeliverDate(jdcDate.getDate());
                    receivingReport.setReceivingWarehouse(txtReceivingWarehouse.getText().trim());
                    receivingReport.setPreparedBy(txtPreparedBy.getText().trim());
                    receivingReport.setCheckedBy(txtCheckedBy.getText().trim());
                    receivingReport.setApprovedBy(txtApprovedBy.getText().trim());
                    receivingReport.setPurchaseOrder(purchaseOrder);
                    receivingReport.setTotalAmount(deliveryTotalAmount);
                    if(ReceivingReportService.save(receivingReport)) {
                        System.err.println("RECEIVING REPORT SUCCESSFULLY SAVED!!");
                        for(int i=0; i<itemOrders.size(); i++) {
                            System.err.println("ITEM ORDERS PANGILAN!!" + i);
                            try {
                                int quantity = Integer.parseInt(((DefaultTableModel)tblDeliveries.getModel()).getValueAt(i, 2).toString().trim());
                                if(quantity > 0) {
                                    ItemOrder itemOrder = itemOrders.get(i);
                                    ItemDelivery itemDelivery = new ItemDelivery();
                                    itemDelivery.setItemOrder(itemOrder);
                                    itemDelivery.setQuantity(quantity);
                                    itemDelivery.setReceivingReport(receivingReport);
                                    if(ItemDeliveryService.save(itemDelivery)) {
                                        System.err.println("ITEM DELIVERY SUCCESSFULLY SAVED!!");
                                        ItemStock itemStock = new ItemStock();
                                        itemStock.setItemCode(itemOrder.getItemCode());
                                        itemStock.setDescription(itemOrder.getDescription());
                                        itemStock.setQuantity(quantity);
                                        itemStock.setUnit(itemOrder.getUnit());
                                        itemStock.setUnitPrice(itemOrder.getUnitPrice());
                                        itemStock.setCurrency(itemOrder.getCurrency());
                                        itemStock.setSupplier(purchaseOrder.getSupplier());
                                        if(ItemStockService.save(itemStock)) {
                                            System.err.println("ITEM STOCK SUCCESSFULLY SAVED");
                                        }
                                    }
                                }
                            } catch(Exception ex) {
                                ex.printStackTrace();
                            }
                        }
                    }
                    if(PurchaseOrderService.isCompleted(purchaseOrder)) {
                        purchaseOrder.setCompleted(true);
                        if(PurchaseOrderService.update(purchaseOrder)) System.out.println("PURCHASE ORDER UPDATED STATUS COMPLETE WITH ID " + purchaseOrder.getId());
                        JOptionPane.showMessageDialog(null, "Receiving Report Successfully saved with no pending item", "COMPLETE DELIVERY", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Receiving Report Successfully saved with pending items", "PARTIAL DELIVERY", JOptionPane.INFORMATION_MESSAGE);
                    }
                    clearFields();
                });
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            dispose();
            frame.setVisible(true);
        });
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReceiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReceiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReceiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReceiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReceiving().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxPoNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcDate;
    private javax.swing.JLabel lblDeliveryDate;
    private javax.swing.JLabel lblDeliveryPlace;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblPoDate;
    private javax.swing.JLabel lblProjectCode;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JLabel lblSupplierCode;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JTable tblDeliveries;
    private javax.swing.JTable tblItemOrders;
    private javax.swing.JTextField txtApprovedBy;
    private javax.swing.JTextField txtCheckedBy;
    private javax.swing.JTextField txtDeliveryTotalAmount;
    private javax.swing.JTextField txtPOTotalAmount;
    private javax.swing.JTextField txtPreparedBy;
    private javax.swing.JTextField txtRRNo;
    private javax.swing.JTextField txtReceivingWarehouse;
    // End of variables declaration//GEN-END:variables

    private void initializeData() {
        deliveryColumn = new Vector<>();
        deliveryColumn.add("Item Code");
        deliveryColumn.add("Description");
        deliveryColumn.add("Qty");
        deliveryColumn.add("Unit");
        deliveryColumn.add("Currency");
        deliveryColumn.add("Unit Price");
        deliveryColumn.add("Total Cost");
        columns = new Vector<>();
        columns.add("Item Code");
        columns.add("Description");
        columns.add("Qty");
        columns.add("Unit");
        columns.add("Currency");
        columns.add("Unit Price");
        columns.add("Total Cost");
        purchaseOrders = PurchaseOrderService.findByCompleted(false);
        System.out.println("PURCHASE ORDER SIZE: " + purchaseOrders.size());
        DefaultComboBoxModel poNoModel = new DefaultComboBoxModel();
        purchaseOrders.forEach(purchaseOrder -> {
            poNoModel.addElement(purchaseOrder.getPoNo());
        });
        SwingUtilities.invokeLater(() -> {
            AutoCompleteDecorator.decorate(cbxPoNo);
            cbxPoNo.setModel(poNoModel);
            cbxPoNo.setSelectedIndex(-1);
            tblItemOrders.setDefaultEditor(Object.class, null);
//            tblDeliveries.setDefaultEditor(Object.class, null);
//            tblItemOrders.setDefaultEditor(Object.class, null);
        });
    }
    
    private void clearFields() {
        tblDeliveries.setModel(new DefaultTableModel(new Vector<>(), columns));
        tblItemOrders.setModel(new DefaultTableModel(new Vector<>(), columns));
        txtRRNo.setText("");
        txtReceivingWarehouse.setText("");
        txtDeliveryTotalAmount.setText("0.00");
        txtPOTotalAmount.setText("0.00");
        jdcDate.setDate(new Date());
        txtCheckedBy.setText("");
        txtApprovedBy.setText("");
        txtPreparedBy.setText("");
        initializeData();
    }
    
    class CustomTableModelListener implements TableModelListener, KeyListener{

        @Override
        public void tableChanged(TableModelEvent e) {
            SwingUtilities.invokeLater(() -> {
                int row = e.getFirstRow();
                int column = e.getColumn();
                if(column == 2) {
                    try {
                        int qty = Integer.parseInt(tblDeliveries.getValueAt(row, 2).toString());
                        BigDecimal quantity = new BigDecimal(qty); 
                        BigDecimal unitPrice = new BigDecimal(Double.parseDouble(tblDeliveries.getValueAt(row, 5).toString()));
                        deliveryTotalAmount.subtract(BigDecimal.valueOf(Double.parseDouble(tblDeliveries.getValueAt(row, 6).toString())));
                        BigDecimal sum = quantity.multiply(unitPrice);
                        tblDeliveries.setValueAt(sum.toString(), row, 6);
                        System.err.println("DELIVERY TOTAL AMOUNT BEFORE SUM: " + deliveryTotalAmount.toString());
                        deliveryTotalAmount = deliveryTotalAmount.add(sum);
                        System.out.println("SUM: " + sum.toString());
                        txtDeliveryTotalAmount.setText(deliveryTotalAmount.toString());
                        System.err.println("DELIVERY TOTAL AMOUNT: " + deliveryTotalAmount.toString());
                    } catch(NumberFormatException ex) {
                        ex.printStackTrace();
                        System.err.println("ERRORED");
                    }
                }
            });
        }

        @Override
        public void keyTyped(KeyEvent e) {
            System.out.println("isko almighty");
        }

        @Override
        public void keyPressed(KeyEvent e) {
            System.out.println("keypressed");
        }

        @Override
        public void keyReleased(KeyEvent e) {
            System.out.println("keyreleased");
        }
        
    }
    
}
