
package Forms.MMD;

import ConstantHandlers.ConstantHandler;
import ConstantHandlers.PublicMethods;
import Entities.Project;
import Entities.Purchases.ItemOrder;
import Entities.Purchases.PurchaseOrder;
import Entities.Supplier;
import Forms.Login;
import Services.ItemOrderService;
import Services.ProjectService;
import Services.PurchaseOrderService;
import Services.SupplierService;
import java.awt.Color;
import java.awt.Frame;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class AddPurchaseOrder extends javax.swing.JFrame {

    Frame frame;
    List<Project> projects;
    List<Supplier> suppliers;
    Vector<Vector> tableData = new Vector<>();
    Vector<String> columns = new Vector<>();
    JTextComponent[] textFields;
    BigDecimal totalAmount;
    
    public AddPurchaseOrder() {
        initComponents();
        initializeData();
    }
    public AddPurchaseOrder(Frame frame) {
        initComponents();
        this.frame = frame;
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPurchaseOrderNo = new javax.swing.JLabel();
        lblLoggedInAs = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdcDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jdcDeliveryDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeliveryPlace = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxTermsOfPayment = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        cbxProjectCode = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxProjectName = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnAddProject = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lblDepartmentPO = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxSupplierCode = new javax.swing.JComboBox<>();
        cbxSupplierName = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btnAddSupplier = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtUnitPrice = new javax.swing.JTextField();
        txtTotalCost = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtUnit = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        cbxCurrency = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnSave = new javax.swing.JMenuItem();
        btnPrint = new javax.swing.JMenuItem();
        btnLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD PURCHASE ORDER");
        setBounds(new java.awt.Rectangle(0, 0, 1936, 1038));
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1936, 1038));
        setSize(new java.awt.Dimension(1936, 1038));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("P.O. No:  ");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 28));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("P.O. Date:  ");

        lblPurchaseOrderNo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPurchaseOrderNo.setText("jLabel3");

        lblLoggedInAs.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblLoggedInAs.setText("jLabel5");
        lblLoggedInAs.setPreferredSize(new java.awt.Dimension(200, 28));

        lblDepartment.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDepartment.setText("jLabel6");
        lblDepartment.setPreferredSize(new java.awt.Dimension(200, 28));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Logged in as:  ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Department:  ");

        jdcDate.setBackground(new java.awt.Color(102, 153, 255));
        jdcDate.setDateFormatString("MMMM-dd-yyyy");
        jdcDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jdcDeliveryDate.setBackground(new java.awt.Color(102, 153, 255));
        jdcDeliveryDate.setDateFormatString("MMMM-dd-yyyy");
        jdcDeliveryDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Delivery Place:  ");

        txtDeliveryPlace.setColumns(20);
        txtDeliveryPlace.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDeliveryPlace.setRows(5);
        jScrollPane1.setViewportView(txtDeliveryPlace);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Terms of Payment:  ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Delivery Date:  ");

        cbxTermsOfPayment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxTermsOfPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash on Delivery", "Pay Pal" }));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        cbxProjectCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxProjectCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProjectCodeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Project Code:  ");
        jLabel9.setPreferredSize(new java.awt.Dimension(121, 22));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Project Name:  ");

        cbxProjectName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProjectNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROJECT INFO");

        btnAddProject.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnAddProject.setText("+");
        btnAddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProjectActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Department:  ");

        lblDepartmentPO.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDepartmentPO.setPreferredSize(new java.awt.Dimension(63, 22));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbxProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddProject))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxProjectCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDepartmentPO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxProjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnAddProject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDepartmentPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Supplier Code:  ");

        cbxSupplierCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxSupplierCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSupplierCodeActionPerformed(evt);
            }
        });

        cbxSupplierName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSupplierNameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Supplier Name:  ");

        btnAddSupplier.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnAddSupplier.setText("+");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jdcDeliveryDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxTermsOfPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddSupplier))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSupplierCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnAddSupplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcDeliveryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(cbxTermsOfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtUnitPrice.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUnitPrice.setToolTipText("Unit Price Field");

        txtTotalCost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalCost.setToolTipText("Total Cost Field");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Currency:  ");
        jLabel18.setPreferredSize(new java.awt.Dimension(104, 22));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Description:  ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Unit Price:  ");
        jLabel16.setPreferredSize(new java.awt.Dimension(104, 22));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Unit:  ");
        jLabel15.setPreferredSize(new java.awt.Dimension(104, 22));

        txtUnit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUnit.setToolTipText("Unit Field");

        txtQuantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtQuantity.setToolTipText("Quantity Field");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Item Code:  ");
        jLabel12.setPreferredSize(new java.awt.Dimension(104, 22));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Total Cost:  ");
        jLabel17.setPreferredSize(new java.awt.Dimension(104, 22));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Quantity:  ");
        jLabel14.setPreferredSize(new java.awt.Dimension(104, 22));

        txtItemCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtItemCode.setToolTipText("Item Code Field");

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDescription.setRows(5);
        txtDescription.setToolTipText("Description Field");
        jScrollPane3.setViewportView(txtDescription);

        btnAdd.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnAdd.setText("Add Item");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cbxCurrency.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PHP", "USD", "EUR", "JPY", "GBP", "KRW", "SGD", "GBP", "CHF", "CAD", "AUD", "NZD", "ZAR" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItemCode))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalCost))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCurrency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnitPrice))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantity))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblOrders.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Quantity", "Unit", "Unit Price", "Currency", "Total Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOrders);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("TOTAL AMOUNT:  ");

        lblTotalAmount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnBack.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPurchaseOrderNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLoggedInAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPurchaseOrderNo)
                    .addComponent(lblLoggedInAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jdcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(254, 254, 254))
        );

        jMenu1.setText("File");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jMenu1.add(btnSave);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jMenu1.add(btnPrint);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(checkDataValidity()) {
            Vector<String> row = new Vector<>();
            row.add(txtItemCode.getText().trim());
            row.add(txtDescription.getText().trim());
            row.add(txtQuantity.getText().trim());
            row.add(txtUnit.getText().trim());
            row.add(txtUnitPrice.getText().trim());
            row.add(cbxCurrency.getSelectedItem().toString());
            row.add(txtTotalCost.getText().trim());
            tableData.add(row);
            tblOrders.setModel(new DefaultTableModel(tableData, columns));
            totalAmount = totalAmount.add(BigDecimal.valueOf(Double.parseDouble(txtTotalCost.getText().trim())));
            lblTotalAmount.setText(totalAmount.toString());
            clearItemField();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            if(evt.getClickCount()>1) {
                JTable source = (JTable)evt.getSource();
                int row = source.rowAtPoint( evt.getPoint());
                int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this row?", "DELETE CREATED ROW?", JOptionPane.OK_CANCEL_OPTION, 3);
                if(confirmation == 0) {
//                    BigDecimal amount = BigDecimal.valueOf(Double.parseDouble(data.get(row).get(6).toString()));
//                    BigDecimal totalAmount = BigDecimal.valueOf(Double.parseDouble(txtTotalAmount.getText()));
//                    totalAmount = totalAmount.subtract(amount);
//                    txtTotalAmount.setText(totalAmount.toString());
                    tableData.remove(row);
                    DefaultTableModel tableModel = new DefaultTableModel(tableData, columns);
                    tblOrders.setModel(tableModel);
                }
            }
        });
    }//GEN-LAST:event_tblOrdersMouseClicked

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        Supplier supplier = PublicMethods.addSupplier(this);
        if(!(supplier == null)) {
            System.err.println("NOT EQUALS NULL");
            SwingUtilities.invokeLater(() -> {
                suppliers.add(supplier);
                ((DefaultComboBoxModel) cbxSupplierCode.getModel()).addElement(supplier.getCode());
                ((DefaultComboBoxModel) cbxSupplierName.getModel()).addElement(supplier.getName());
            });
        } else {
            System.err.println("EQUALS NULL");
        }
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnAddProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProjectActionPerformed
        Project project = PublicMethods.addProject(this);
        if(!(project == null)) {
            SwingUtilities.invokeLater(() -> {
                projects.add(project);
                ((DefaultComboBoxModel) cbxProjectName.getModel()).addElement(project.getProjectName());
                ((DefaultComboBoxModel) cbxProjectCode.getModel()).addElement(project.getProjectCode());
            });
        }
    }//GEN-LAST:event_btnAddProjectActionPerformed

    private void cbxSupplierCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSupplierCodeActionPerformed
        SwingUtilities.invokeLater(() -> {
            cbxSupplierName.setSelectedIndex(cbxSupplierCode.getSelectedIndex());
        });
    }//GEN-LAST:event_cbxSupplierCodeActionPerformed

    private void cbxSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSupplierNameActionPerformed
        SwingUtilities.invokeLater(() -> {
            cbxSupplierCode.setSelectedIndex(cbxSupplierName.getSelectedIndex());
        });
    }//GEN-LAST:event_cbxSupplierNameActionPerformed

    private void cbxProjectCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProjectCodeActionPerformed
        SwingUtilities.invokeLater(() -> {
            int index = cbxProjectCode.getSelectedIndex();
            cbxProjectName.setSelectedIndex(index);
            lblDepartmentPO.setText(projects.get(index).getDepartment().getName());
        });
    }//GEN-LAST:event_cbxProjectCodeActionPerformed

    private void cbxProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProjectNameActionPerformed
        SwingUtilities.invokeLater(() -> {
            int index = cbxProjectName.getSelectedIndex();
            cbxProjectCode.setSelectedIndex(index);
            lblDepartmentPO.setText(projects.get(index).getDepartment().getName());
        });
    }//GEN-LAST:event_cbxProjectNameActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       SwingUtilities.invokeLater(() -> {
           ConstantHandler.user = null;
           dispose();
           new Login().setVisible(true);
       });
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(validateData()) {
            int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to save this PO?", "CONFIRM TO SAVE PO?", JOptionPane.OK_CANCEL_OPTION, 3);
            if(confirmation == 0) {
                PurchaseOrder purchaseOrder = new PurchaseOrder();
                purchaseOrder.setCreatedBy(ConstantHandler.user);
                purchaseOrder.setCreatedAt(new Date());
                purchaseOrder.setPoNo(lblPurchaseOrderNo.getText());
                purchaseOrder.setPoDate(jdcDate.getDate());
                purchaseOrder.setDeliveryDate(jdcDeliveryDate.getDate());
                purchaseOrder.setDeliveryPlace(txtDeliveryPlace.getText());
                purchaseOrder.setTermOfPayment(cbxTermsOfPayment.getSelectedItem().toString());
                purchaseOrder.setTotalAmount(totalAmount);
                purchaseOrder.setSupplier(suppliers.get(cbxSupplierCode.getSelectedIndex()));
                purchaseOrder.setProject(projects.get(cbxProjectCode.getSelectedIndex()));
                purchaseOrder.setCompleted(false);
                if(PurchaseOrderService.save(purchaseOrder)) {
                    JOptionPane.showMessageDialog(null, "SAVE SUCCESSFULL");
                }
                tableData.forEach(row -> {
                    String itemCode = String.valueOf(row.get(0));
                    String description = String.valueOf(row.get(1));
                    int quantity = Integer.parseInt(String.valueOf(row.get(2)));
                    String unit = String.valueOf(row.get(3));
                    BigDecimal unitPrice = BigDecimal.valueOf(Double.parseDouble(String.valueOf(row.get(4))));
                    String currency = String.valueOf(row.get(5));
                    BigDecimal totalCost = BigDecimal.valueOf(Double.parseDouble(String.valueOf(row.get(6))));
                    ItemOrder itemOrder = new ItemOrder(itemCode, description, quantity, unit, unitPrice, currency, totalCost);
                    itemOrder.setPurchaseOrder(purchaseOrder);
                    if(ItemOrderService.save(itemOrder)) {
                        System.err.println("ITEM ORDER SAVED!!");
                    }
                });
                tableData = new Vector<>();
                tblOrders.setModel(new DefaultTableModel(tableData, columns));
                totalAmount = new BigDecimal(0);
                lblTotalAmount.setText(totalAmount.toString());
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        String reportPath = "C:\\Users\\user\\Documents\\Netbeans Projects\\MGExeo\\src\\main\\java\\Forms\\MMD\\purchaseOrder.jrxml";
        Supplier supplier = suppliers.get(cbxSupplierCode.getSelectedIndex());
        List<Map<String, Object>> dataSource = new ArrayList<Map<String, Object>>();
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("vendor_company", supplier.getName());
        parameters.put("vendor_address", supplier.getAddress());
        parameters.put("vendor_telephone", supplier.getTelephone());
        parameters.put("vendor_fax", supplier.getFaxNo());
        parameters.put("po_no", lblPurchaseOrderNo.getText());
        parameters.put("order_date", jdcDate.getDate());
        parameters.put("attention", "Sample Attention");
        parameters.put("delivery_place", txtDeliveryPlace.getText().trim());
        parameters.put("delivery_date", jdcDeliveryDate.getDate());
        parameters.put("terms_of_payment", cbxTermsOfPayment.getSelectedItem().toString());
        tableData.forEach(data -> {
            Map<String, Object> row = new HashMap<>();
            row.put("itemCode", data.get(0).toString());
            row.put("description", data.get(1).toString());
            row.put("qty", Integer.parseInt(data.get(2).toString()));
            row.put("unit", data.get(3).toString());
            row.put("currency", data.get(5).toString());
            row.put("unitPrice", BigDecimal.valueOf(Double.parseDouble(data.get(4).toString())));
            row.put("totalCost", BigDecimal.valueOf(Double.parseDouble(data.get(6).toString())));
            dataSource.add(row);
        });
        
        try {
            JRDataSource jRDataSource = new JRBeanCollectionDataSource(dataSource);
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jr, parameters, jRDataSource);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            jasperViewer.setVisible(true);
            
        } catch (Exception ex) {
            Logger.getLogger(AddPurchaseOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            dispose();
            frame.setVisible(true);
        });
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPurchaseOrder().setVisible(true);
            }
        });
    }

    // <editor-fold defaultstate="collapsed" desc="Object element Variables">    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddProject;
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnBack;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JMenuItem btnPrint;
    private javax.swing.JMenuItem btnSave;
    private javax.swing.JComboBox<String> cbxCurrency;
    private javax.swing.JComboBox<String> cbxProjectCode;
    private javax.swing.JComboBox<String> cbxProjectName;
    private javax.swing.JComboBox<String> cbxSupplierCode;
    private javax.swing.JComboBox<String> cbxSupplierName;
    private javax.swing.JComboBox<String> cbxTermsOfPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcDate;
    private com.toedter.calendar.JDateChooser jdcDeliveryDate;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartmentPO;
    private javax.swing.JLabel lblLoggedInAs;
    private javax.swing.JLabel lblPurchaseOrderNo;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextArea txtDeliveryPlace;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
    // </editor-fold >
    
    private void initializeData() {
        columns.add("Item Code");
        columns.add("Description");
        columns.add("Qty");
        columns.add("Unit");
        columns.add("Unit Price");
        columns.add("Currency");
        columns.add("Total Amount");
        totalAmount = new BigDecimal(0);
        textFields = new JTextComponent[]{txtItemCode, txtDescription, txtQuantity, txtUnit, txtUnitPrice, txtTotalCost};
        projects = ProjectService.findAll();
        suppliers = SupplierService.findAll();
        DefaultComboBoxModel projectNameModel = new DefaultComboBoxModel();
        DefaultComboBoxModel projectCodeModel = new DefaultComboBoxModel();
        DefaultComboBoxModel supplierCodeModel = new DefaultComboBoxModel();
        DefaultComboBoxModel supplierNameModel = new DefaultComboBoxModel();
        tblOrders.setDefaultEditor(Object.class, null);
        projects.forEach(project -> {
            projectNameModel.addElement(project.getProjectName());
            projectCodeModel.addElement(project.getProjectCode());
        });
        suppliers.forEach(supplier -> {
            supplierCodeModel.addElement(supplier.getCode());
            supplierNameModel.addElement(supplier.getName());
        });
        SwingUtilities.invokeLater(() -> {
            lblPurchaseOrderNo.setText(PurchaseOrderService.generatePONo());
            lblLoggedInAs.setText(ConstantHandler.user.getUsername());
            lblDepartment.setText(ConstantHandler.user.getDepartment().getName());
            jdcDate.setDate(new Date());
            AutoCompleteDecorator.decorate(cbxProjectCode);
            AutoCompleteDecorator.decorate(cbxProjectName);
            AutoCompleteDecorator.decorate(cbxSupplierCode);
            AutoCompleteDecorator.decorate(cbxSupplierName);
            cbxProjectCode.setModel(projectCodeModel);
            cbxProjectName.setModel(projectNameModel);
            cbxSupplierCode.setModel(supplierCodeModel);
            cbxSupplierName.setModel(supplierNameModel);
            lblTotalAmount.setText(totalAmount.toString());
        });
        for(JTextComponent field: textFields) {
            field.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    if(field.equals(txtQuantity) || field.equals(txtUnitPrice)) {
                        if(!(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar() == '.')) {
                            evt.consume();

                        } else if(evt.getKeyChar() == '.' && field.getText().indexOf(".") > -1) {
                                evt.consume();
                        }else {
                            SwingUtilities.invokeLater(() -> {
                                if(!(txtQuantity.getText().equals("")) && !(txtUnitPrice.getText().equals(""))) {
                                    BigDecimal quantity = BigDecimal.valueOf(Double.parseDouble(txtQuantity.getText().trim()));
                                    BigDecimal unitPrice = BigDecimal.valueOf(Double.parseDouble(txtUnitPrice.getText().trim()));
                                    BigDecimal totalCost = quantity.multiply(unitPrice);
                                    txtTotalCost.setText(totalCost.toPlainString());
                                }
                            });
                        } 
                    }
                    SwingUtilities.invokeLater(() -> {
                        if(field.getText().equals("")) {
                            field.setBackground(new Color(255, 51, 51));
                        } else {
                            field.setBackground(new Color(255, 255, 255));
                        }
                    });
                }
            });
        }
    }

    private boolean checkDataValidity() {
        for(JTextComponent field: textFields) {
            if(field.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please specify value on " + field.getToolTipText(), "INCOMPLETE FIELD", JOptionPane.ERROR_MESSAGE);
                field.setBackground(Color.RED);
                return false;
            }
        }
        return true;
    }

    private boolean validateData() {
        if(tableData.size() < 1) {
            JOptionPane.showMessageDialog(null, "No Items Found!", "SAVE DENIED", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(txtDeliveryPlace.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please specify the delivery place!", "SAVE DENIED", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            Date date = jdcDeliveryDate.getDate();
            System.out.println(date.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please specify the delivery date!", "SAVE DENIED", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }

    private void clearItemField() {
        txtItemCode.setText("");
        txtDescription.setText("");
        txtQuantity.setText("");
        txtUnit.setText("");
        txtUnitPrice.setText("");
        txtTotalCost.setText("");
        cbxCurrency.setSelectedIndex(0);
    }
    
}
